# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_REJECT_REJECTTYPE = descriptor.EnumDescriptor(
  name='RejectType',
  full_name='MumbleProto.Reject.RejectType',
  filename='RejectType',
  values=[
    descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WrongVersion', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='InvalidUsername', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WrongUserPW', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WrongServerPW', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UsernameInUse', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ServerFull', index=6, number=6,
      options=None,
      type=None),
  ],
  options=None,
)

_PERMISSIONDENIED_DENYTYPE = descriptor.EnumDescriptor(
  name='DenyType',
  full_name='MumbleProto.PermissionDenied.DenyType',
  filename='DenyType',
  values=[
    descriptor.EnumValueDescriptor(
      name='Text', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Permission', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SuperUser', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ChannelName', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TextTooLong', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='H9K', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TemporaryChannel', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MissingCertificate', index=7, number=7,
      options=None,
      type=None),
  ],
  options=None,
)

_CONTEXTACTIONADD_CONTEXT = descriptor.EnumDescriptor(
  name='Context',
  full_name='MumbleProto.ContextActionAdd.Context',
  filename='Context',
  values=[
    descriptor.EnumValueDescriptor(
      name='Server', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Channel', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='User', index=2, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


_VERSION = descriptor.Descriptor(
  name='Version',
  full_name='MumbleProto.Version',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='MumbleProto.Version.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='release', full_name='MumbleProto.Version.release', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='os', full_name='MumbleProto.Version.os', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='os_version', full_name='MumbleProto.Version.os_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_UDPTUNNEL = descriptor.Descriptor(
  name='UDPTunnel',
  full_name='MumbleProto.UDPTunnel',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='packet', full_name='MumbleProto.UDPTunnel.packet', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_AUTHENTICATE = descriptor.Descriptor(
  name='Authenticate',
  full_name='MumbleProto.Authenticate',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='username', full_name='MumbleProto.Authenticate.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='MumbleProto.Authenticate.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tokens', full_name='MumbleProto.Authenticate.tokens', index=2,
      number=3, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='celt_versions', full_name='MumbleProto.Authenticate.celt_versions', index=3,
      number=4, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PING = descriptor.Descriptor(
  name='Ping',
  full_name='MumbleProto.Ping',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='MumbleProto.Ping.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='good', full_name='MumbleProto.Ping.good', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='late', full_name='MumbleProto.Ping.late', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lost', full_name='MumbleProto.Ping.lost', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resync', full_name='MumbleProto.Ping.resync', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='udp_packets', full_name='MumbleProto.Ping.udp_packets', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tcp_packets', full_name='MumbleProto.Ping.tcp_packets', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='udp_ping_avg', full_name='MumbleProto.Ping.udp_ping_avg', index=7,
      number=8, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='udp_ping_var', full_name='MumbleProto.Ping.udp_ping_var', index=8,
      number=9, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tcp_ping_avg', full_name='MumbleProto.Ping.tcp_ping_avg', index=9,
      number=10, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tcp_ping_var', full_name='MumbleProto.Ping.tcp_ping_var', index=10,
      number=11, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REJECT = descriptor.Descriptor(
  name='Reject',
  full_name='MumbleProto.Reject',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='MumbleProto.Reject.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='MumbleProto.Reject.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _REJECT_REJECTTYPE,
  ],
  options=None)


_SERVERSYNC = descriptor.Descriptor(
  name='ServerSync',
  full_name='MumbleProto.ServerSync',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.ServerSync.session', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_bandwidth', full_name='MumbleProto.ServerSync.max_bandwidth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='welcome_text', full_name='MumbleProto.ServerSync.welcome_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='permissions', full_name='MumbleProto.ServerSync.permissions', index=3,
      number=4, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='allow_html', full_name='MumbleProto.ServerSync.allow_html', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CHANNELREMOVE = descriptor.Descriptor(
  name='ChannelRemove',
  full_name='MumbleProto.ChannelRemove',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.ChannelRemove.channel_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CHANNELSTATE = descriptor.Descriptor(
  name='ChannelState',
  full_name='MumbleProto.ChannelState',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.ChannelState.channel_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parent', full_name='MumbleProto.ChannelState.parent', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='MumbleProto.ChannelState.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='links', full_name='MumbleProto.ChannelState.links', index=3,
      number=4, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='MumbleProto.ChannelState.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='links_add', full_name='MumbleProto.ChannelState.links_add', index=5,
      number=6, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='links_remove', full_name='MumbleProto.ChannelState.links_remove', index=6,
      number=7, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temporary', full_name='MumbleProto.ChannelState.temporary', index=7,
      number=8, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='MumbleProto.ChannelState.position', index=8,
      number=9, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_USERREMOVE = descriptor.Descriptor(
  name='UserRemove',
  full_name='MumbleProto.UserRemove',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.UserRemove.session', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actor', full_name='MumbleProto.UserRemove.actor', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='MumbleProto.UserRemove.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ban', full_name='MumbleProto.UserRemove.ban', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_USERSTATE = descriptor.Descriptor(
  name='UserState',
  full_name='MumbleProto.UserState',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.UserState.session', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actor', full_name='MumbleProto.UserState.actor', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='MumbleProto.UserState.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_id', full_name='MumbleProto.UserState.user_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.UserState.channel_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mute', full_name='MumbleProto.UserState.mute', index=5,
      number=6, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deaf', full_name='MumbleProto.UserState.deaf', index=6,
      number=7, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suppress', full_name='MumbleProto.UserState.suppress', index=7,
      number=8, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='self_mute', full_name='MumbleProto.UserState.self_mute', index=8,
      number=9, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='self_deaf', full_name='MumbleProto.UserState.self_deaf', index=9,
      number=10, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='texture', full_name='MumbleProto.UserState.texture', index=10,
      number=11, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='plugin_context', full_name='MumbleProto.UserState.plugin_context', index=11,
      number=12, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='plugin_identity', full_name='MumbleProto.UserState.plugin_identity', index=12,
      number=13, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='MumbleProto.UserState.comment', index=13,
      number=14, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hash', full_name='MumbleProto.UserState.hash', index=14,
      number=15, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_BANLIST_BANENTRY = descriptor.Descriptor(
  name='BanEntry',
  full_name='MumbleProto.BanList.BanEntry',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='address', full_name='MumbleProto.BanList.BanEntry.address', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mask', full_name='MumbleProto.BanList.BanEntry.mask', index=1,
      number=2, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='MumbleProto.BanList.BanEntry.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hash', full_name='MumbleProto.BanList.BanEntry.hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='MumbleProto.BanList.BanEntry.reason', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start', full_name='MumbleProto.BanList.BanEntry.start', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='duration', full_name='MumbleProto.BanList.BanEntry.duration', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_BANLIST = descriptor.Descriptor(
  name='BanList',
  full_name='MumbleProto.BanList',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bans', full_name='MumbleProto.BanList.bans', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query', full_name='MumbleProto.BanList.query', index=1,
      number=2, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TEXTMESSAGE = descriptor.Descriptor(
  name='TextMessage',
  full_name='MumbleProto.TextMessage',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='actor', full_name='MumbleProto.TextMessage.actor', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.TextMessage.session', index=1,
      number=2, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.TextMessage.channel_id', index=2,
      number=3, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tree_id', full_name='MumbleProto.TextMessage.tree_id', index=3,
      number=4, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='MumbleProto.TextMessage.message', index=4,
      number=5, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PERMISSIONDENIED = descriptor.Descriptor(
  name='PermissionDenied',
  full_name='MumbleProto.PermissionDenied',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='permission', full_name='MumbleProto.PermissionDenied.permission', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.PermissionDenied.channel_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.PermissionDenied.session', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='MumbleProto.PermissionDenied.reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='MumbleProto.PermissionDenied.type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _PERMISSIONDENIED_DENYTYPE,
  ],
  options=None)


_ACL_CHANGROUP = descriptor.Descriptor(
  name='ChanGroup',
  full_name='MumbleProto.ACL.ChanGroup',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='MumbleProto.ACL.ChanGroup.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inherited', full_name='MumbleProto.ACL.ChanGroup.inherited', index=1,
      number=2, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inherit', full_name='MumbleProto.ACL.ChanGroup.inherit', index=2,
      number=3, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inheritable', full_name='MumbleProto.ACL.ChanGroup.inheritable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='add', full_name='MumbleProto.ACL.ChanGroup.add', index=4,
      number=5, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remove', full_name='MumbleProto.ACL.ChanGroup.remove', index=5,
      number=6, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inherited_members', full_name='MumbleProto.ACL.ChanGroup.inherited_members', index=6,
      number=7, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_ACL_CHANACL = descriptor.Descriptor(
  name='ChanACL',
  full_name='MumbleProto.ACL.ChanACL',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='apply_here', full_name='MumbleProto.ACL.ChanACL.apply_here', index=0,
      number=1, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='apply_subs', full_name='MumbleProto.ACL.ChanACL.apply_subs', index=1,
      number=2, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inherited', full_name='MumbleProto.ACL.ChanACL.inherited', index=2,
      number=3, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_id', full_name='MumbleProto.ACL.ChanACL.user_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='MumbleProto.ACL.ChanACL.group', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='grant', full_name='MumbleProto.ACL.ChanACL.grant', index=5,
      number=6, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deny', full_name='MumbleProto.ACL.ChanACL.deny', index=6,
      number=7, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_ACL = descriptor.Descriptor(
  name='ACL',
  full_name='MumbleProto.ACL',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.ACL.channel_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inherit_acls', full_name='MumbleProto.ACL.inherit_acls', index=1,
      number=2, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='groups', full_name='MumbleProto.ACL.groups', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='acls', full_name='MumbleProto.ACL.acls', index=3,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query', full_name='MumbleProto.ACL.query', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_QUERYUSERS = descriptor.Descriptor(
  name='QueryUsers',
  full_name='MumbleProto.QueryUsers',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ids', full_name='MumbleProto.QueryUsers.ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='names', full_name='MumbleProto.QueryUsers.names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CRYPTSETUP = descriptor.Descriptor(
  name='CryptSetup',
  full_name='MumbleProto.CryptSetup',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='MumbleProto.CryptSetup.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_nonce', full_name='MumbleProto.CryptSetup.client_nonce', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_nonce', full_name='MumbleProto.CryptSetup.server_nonce', index=2,
      number=3, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CONTEXTACTIONADD = descriptor.Descriptor(
  name='ContextActionAdd',
  full_name='MumbleProto.ContextActionAdd',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='action', full_name='MumbleProto.ContextActionAdd.action', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='MumbleProto.ContextActionAdd.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='context', full_name='MumbleProto.ContextActionAdd.context', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _CONTEXTACTIONADD_CONTEXT,
  ],
  options=None)


_CONTEXTACTION = descriptor.Descriptor(
  name='ContextAction',
  full_name='MumbleProto.ContextAction',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.ContextAction.session', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.ContextAction.channel_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='MumbleProto.ContextAction.action', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_USERLIST_USER = descriptor.Descriptor(
  name='User',
  full_name='MumbleProto.UserList.User',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user_id', full_name='MumbleProto.UserList.User.user_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='MumbleProto.UserList.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_USERLIST = descriptor.Descriptor(
  name='UserList',
  full_name='MumbleProto.UserList',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='users', full_name='MumbleProto.UserList.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VOICETARGET_TARGET = descriptor.Descriptor(
  name='Target',
  full_name='MumbleProto.VoiceTarget.Target',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session', full_name='MumbleProto.VoiceTarget.Target.session', index=0,
      number=1, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.VoiceTarget.Target.channel_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='MumbleProto.VoiceTarget.Target.group', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='links', full_name='MumbleProto.VoiceTarget.Target.links', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='children', full_name='MumbleProto.VoiceTarget.Target.children', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_VOICETARGET = descriptor.Descriptor(
  name='VoiceTarget',
  full_name='MumbleProto.VoiceTarget',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='MumbleProto.VoiceTarget.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='targets', full_name='MumbleProto.VoiceTarget.targets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PERMISSIONQUERY = descriptor.Descriptor(
  name='PermissionQuery',
  full_name='MumbleProto.PermissionQuery',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='MumbleProto.PermissionQuery.channel_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='permissions', full_name='MumbleProto.PermissionQuery.permissions', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flush', full_name='MumbleProto.PermissionQuery.flush', index=2,
      number=3, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CODECVERSION = descriptor.Descriptor(
  name='CodecVersion',
  full_name='MumbleProto.CodecVersion',
  filename='Mumble.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='alpha', full_name='MumbleProto.CodecVersion.alpha', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='beta', full_name='MumbleProto.CodecVersion.beta', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prefer_alpha', full_name='MumbleProto.CodecVersion.prefer_alpha', index=2,
      number=3, type=8, cpp_type=7, label=2,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REJECT.fields_by_name['type'].enum_type = _REJECT_REJECTTYPE
_BANLIST.fields_by_name['bans'].message_type = _BANLIST_BANENTRY
_ACL.fields_by_name['groups'].message_type = _ACL_CHANGROUP
_ACL.fields_by_name['acls'].message_type = _ACL_CHANACL
_USERLIST.fields_by_name['users'].message_type = _USERLIST_USER
_VOICETARGET.fields_by_name['targets'].message_type = _VOICETARGET_TARGET

class Version(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERSION

class UDPTunnel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UDPTUNNEL

class Authenticate(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHENTICATE

class Ping(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PING

class Reject(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REJECT

class ServerSync(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERSYNC

class ChannelRemove(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHANNELREMOVE

class ChannelState(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHANNELSTATE

class UserRemove(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERREMOVE

class UserState(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERSTATE

class BanList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class BanEntry(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BANLIST_BANENTRY
  DESCRIPTOR = _BANLIST

class TextMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEXTMESSAGE

class PermissionDenied(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERMISSIONDENIED

class ACL(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class ChanGroup(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACL_CHANGROUP
  
  class ChanACL(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACL_CHANACL
  DESCRIPTOR = _ACL

class QueryUsers(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYUSERS

class CryptSetup(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CRYPTSETUP

class ContextActionAdd(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTEXTACTIONADD

class ContextAction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTEXTACTION

class UserList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class User(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _USERLIST_USER
  DESCRIPTOR = _USERLIST

class VoiceTarget(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Target(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _VOICETARGET_TARGET
  DESCRIPTOR = _VOICETARGET

class PermissionQuery(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERMISSIONQUERY

class CodecVersion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CODECVERSION

